-- AlterTable
ALTER TABLE "fixtures" ADD COLUMN     "stats_entered" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "gameweek_player_stats" ADD COLUMN     "assists" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "bonus_points" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "goals_scored" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "minutes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "red_cards" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "yellow_cards" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "points" SET DEFAULT 0;
